In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os

# Add the parent directory to the Python path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))
import src.config as config

In [3]:
from src.inference import get_feature_store

In [4]:
from datetime import datetime, timedelta
import pandas as pd  

# Get the current datetime64[us, Etc/UTC]  
current_date = pd.Timestamp.now(tz='Etc/UTC')
feature_store = get_feature_store()

# read time-series data from the feature store
fetch_data_to = current_date - timedelta(hours=1)
fetch_data_from = current_date - timedelta(days=1*29)
print(f"Fetching data from {fetch_data_from} to {fetch_data_to}")
feature_view = feature_store.get_feature_view(
    name=config.FEATURE_VIEW_NAME, version=config.FEATURE_VIEW_VERSION
)

ts_data = feature_view.get_batch_data(
    start_time=(fetch_data_from - timedelta(days=1)),
    end_time=(fetch_data_to + timedelta(days=1)),
)
ts_data = ts_data[ts_data.pickup_hour.between(fetch_data_from, fetch_data_to)]

2025-03-03 03:06:15,679 INFO: Initializing external client
2025-03-03 03:06:15,679 INFO: Base URL: https://c.app.hopsworks.ai:443
2025-03-03 03:06:17,347 INFO: Python Engine initialized.

Logged in to project, explore it here https://c.app.hopsworks.ai:443/p/1213633
Fetching data from 2025-02-02 08:06:15.673238+00:00 to 2025-03-03 07:06:15.673238+00:00
Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (12.36s)

In [5]:
ts_data.sort_values(["pickup_location_id", "pickup_hour"]).reset_index(drop=True)

                     pickup_hour  pickup_location_id  rides
0      2025-02-02 09:00:00+00:00                   2      0
1      2025-02-02 10:00:00+00:00                   2      0
2      2025-02-02 11:00:00+00:00                   2      0
3      2025-02-02 12:00:00+00:00                   2      0
4      2025-02-02 13:00:00+00:00                   2      0
...                          ...                 ...    ...
175352 2025-03-03 03:00:00+00:00                 263      4
175353 2025-03-03 04:00:00+00:00                 263      9
175354 2025-03-03 05:00:00+00:00                 263     14
175355 2025-03-03 06:00:00+00:00                 263     58
175356 2025-03-03 07:00:00+00:00                 263    123

[175357 rows x 3 columns]

In [6]:
ts_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 175357 entries, 0 to 181428
Data columns (total 3 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   pickup_hour         175357 non-null  datetime64[us, Etc/UTC]
 1   pickup_location_id  175357 non-null  int32
 2   rides               175357 non-null  int32
dtypes: datetime64[us, Etc/UTC](1), int32(2)
memory usage: 4.0 MB

In [7]:
ts_data["pickup_hour"] = ts_data["pickup_hour"].dt.tz_localize(None)

In [8]:
ts_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 175357 entries, 0 to 181428
Data columns (total 3 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   pickup_hour         175357 non-null  datetime64[us]
 1   pickup_location_id  175357 non-null  int32
 2   rides               175357 non-null  int32
dtypes: datetime64[us](1), int32(2)
memory usage: 4.0 MB

In [9]:
from src.data_utils import transform_ts_data_info_features
features = transform_ts_data_info_features(ts_data, window_size=24*28, step_size=23)

Skipping location_id 156: Not enough data to create even one window.
Skipping location_id 84: Not enough data to create even one window.

In [10]:
features

,rides_t-672,rides_t-671,rides_t-670,rides_t-669,rides_t-668,rides_t-667,rides_t-666,rides_t-665,rides_t-664,rides_t-663,...,rides_t-8,rides_t-7,rides_t-6,rides_t-5,rides_t-4,rides_t-3,rides_t-2,rides_t-1,pickup_location_id,pickup_hour
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,147,2025-02-11 02:00:00
1,3,2,2,2,1,4,4,1,0,3,...,2,9,4,1,0,2,5,5,65,2025-02-12 11:00:00
2,1,0,0,0,0,1,2,0,0,0,...,0,0,0,0,0,0,0,0,155,2025-02-08 06:00:00
3,0,1,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,85,2025-02-10 05:00:00
4,154,36,94,130,287,234,274,173,231,235,...,361,280,112,204,120,11,240,4,132,2025-02-04 17:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,12,5,2,21,6,9,14,11,9,1,...,16,12,0,28,3,12,10,0,24,2025-02-05 08:00:00
247,51,35,78,49,19,48,1,68,54,2,...,56,49,24,63,1,4,35,58,151,2025-02-11 23:00:00
248,0,1,1,0,0,0,1,0,0,3,...,1,1,0,0,0,0,0,0,119,2025-02-07 23:00:00
249,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,94,2025-02-03 00:00:00
250,0,1,1,0,0,0,1,2,3,0,...,0,0,0,0,1,0,0,0,36,2025-02-05 08:00:00

In [11]:
from src.inference import load_batch_of_features_from_store
current_date = pd.Timestamp.now(tz='Etc/UTC')
features = load_batch_of_features_from_store(current_date)

2025-03-03 03:06:41,982 INFO: Closing external client and cleaning up certificates.
Connection closed.
2025-03-03 03:06:41,997 INFO: Initializing external client
2025-03-03 03:06:41,997 INFO: Base URL: https://c.app.hopsworks.ai:443
2025-03-03 03:06:43,396 INFO: Python Engine initialized.

Logged in to project, explore it here https://c.app.hopsworks.ai:443/p/1213633
Fetching data from 2025-02-02 08:06:41.982904+00:00 to 2025-03-03 07:06:41.982904+00:00
Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (4.54s)
Skipping location_id 84: Not enough data to create even one window.
Skipping location_id 156: Not enough data to create even one window.

In [12]:
current_date

Timestamp('2025-03-03 08:06:41.982904+0000', tz='Etc/UTC')

In [13]:
features

,rides_t-672,rides_t-671,rides_t-670,rides_t-669,rides_t-668,rides_t-667,rides_t-666,rides_t-665,rides_t-664,rides_t-663,...,rides_t-8,rides_t-7,rides_t-6,rides_t-5,rides_t-4,rides_t-3,rides_t-2,rides_t-1,pickup_location_id,pickup_hour
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,2025-03-02 09:00:00
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,3,2025-03-02 09:00:00
2,3,0,4,3,2,5,0,7,2,8,...,62,65,43,15,0,1,0,1,4,2025-03-02 09:00:00
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,6,2025-03-02 09:00:00
4,6,4,3,1,3,1,6,2,0,0,...,1,1,3,3,2,1,1,1,7,2025-03-02 09:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,259,2025-03-02 09:00:00
247,1,1,2,0,3,1,0,0,1,4,...,0,0,0,0,0,2,0,0,260,2025-03-02 09:00:00
248,14,9,30,28,30,28,38,26,37,26,...,12,7,10,2,1,2,3,7,261,2025-03-02 09:00:00
249,59,85,107,91,91,76,75,59,61,46,...,5,5,2,5,8,10,25,50,262,2025-03-02 09:00:00
250,80,114,133,156,127,128,132,94,86,113,...,49,41,29,17,9,30,34,69,263,2025-03-02 09:00:00

In [14]:
from src.inference import load_model_from_registry

model = load_model_from_registry()

2025-03-03 03:07:01,399 INFO: Closing external client and cleaning up certificates.
Connection closed.
2025-03-03 03:07:01,412 INFO: Initializing external client
2025-03-03 03:07:01,413 INFO: Base URL: https://c.app.hopsworks.ai:443
2025-03-03 03:07:02,792 INFO: Python Engine initialized.

Logged in to project, explore it here https://c.app.hopsworks.ai:443/p/1213633
Downloading model artifact (0 dirs, 1 files)... DONE

In [15]:
from src.inference import get_model_predictions
predictions = get_model_predictions(model, features)

In [16]:
predictions

     pickup_location_id  predicted_demand
0                     2               0.0
1                     3               0.0
2                     4               2.0
3                     6               0.0
4                     7               3.0
..                  ...               ...
246                 259               1.0
247                 260               1.0
248                 261              14.0
249                 262              68.0
250                 263              90.0

[251 rows x 2 columns]

In [17]:
predictions.sort_values("predicted_demand", ascending=False).head(10)["pickup_location_id"].values

array([236, 230, 132, 239, 237, 238, 142, 186, 141, 263])